name: FancyGlow
description: "Plugin that allow the player to change its glowing color."
author: hhitt
version: '${project.version}'
main: hhitt.fancyglow.FancyGlow
api-version: '1.20'
softdepend: [ PlaceholderAPI ]
commands:
  glow:
    description: Main FancyGlow command used to toggle or select your glow mode.
    usage: /<command>
    aliases:
      - fancyglow

permissions:
  fancyglow.admin:
    description: Gives permission to every FancyGlow command and feature.
    default: op
    children:
      fancyglow.rainbow: true
      fancyglow.all_colors: true
      fancyglow.command.gui: true
      fancyglow.command.color: true
      fancyglow.command.reload: true
      fancyglow.command.disable: true
      fancyglow.command.disable.everyone: true
      fancyglow.command.disable.others: true